backend:
  name: git-gateway
  branch: main # ✅ IMPORTANTE: Cambia a 'master' si esa es tu rama principal en GitHub/Git.

# Habilita el Identity service de Netlify
publish_mode: editorial_workflow # Opcional: para permitir borradores y revisiones antes de publicar. Si quieres publicar directamente, usa 'simple'
media_folder: "static/img/uploads" # Dónde se guardarán las imágenes en tu repositorio
public_folder: "/img/uploads" # La ruta pública para las imágenes en tu sitio

# --- COLECCIONES (Ejemplo) ---
# Debes adaptar esto a la estructura de contenido de tu sitio.

collections:
  - name: "pages" # Nombre de la colección (usado internamente)
    label: "Páginas del Sitio" # Etiqueta que verás en el CMS
    files:
      - file: "src/data/home.md" # Ruta real del archivo a modificar
        label: "Página de Inicio"
        name: "home"
        fields:
          - {label: "Título Principal", name: "title", widget: "string"}
          - {label: "Cuerpo del Texto", name: "body", widget: "markdown"}
      - file: "src/data/about.md"
        label: "Página Nosotros"
        name: "about"
        fields:
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Contenido", name: "content", widget: "text"}

  - name: "blog" # Colección de publicaciones de blog (usa carpetas)
    label: "Blog Posts"
    folder: "src/posts" # Carpeta donde se guardan tus archivos de blog (ej. Markdown)
    create: true # Permite crear nuevas publicaciones
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Formato de nombre de archivo
    fields: # Los campos que tendrá cada publicación
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Imagen destacada", name: "thumbnail", widget: "image", required: false}
      - {label: "Cuerpo", name: "body", widget: "markdown"}
