backend:
  name: git-gateway
  # ✅ IMPORTANTE: Mantén 'main' si esa es tu rama principal.
  branch: main 

# Habilita el Identity service de Netlify
publish_mode: editorial_workflow # 'editorial_workflow' para borradores, 'simple' para publicación directa.
# Rutas de imágenes corregidas
media_folder: "static/uploads" # ⬅️ CORREGIDO: Usando 'static/uploads' ya que no existe 'static/img'.
public_folder: "/uploads" # La ruta pública que usará el sitio para acceder a las imágenes.
# Asegúrate de crear manualmente la carpeta 'static/uploads' en tu repositorio si no existe.

# --- COLECCIONES CORREGIDAS ---
collections:
  - name: "pages" # Colección de archivos individuales
    label: "Páginas del Sitio"
    files:
      # ⬅️ RUTA CORREGIDA: Apunta a 'content/pages/home.md'
      - file: "content/pages/home.md" 
        label: "Página de Inicio"
        name: "home"
        fields:
          - {label: "Título Principal", name: "title", widget: "string"}
          - {label: "Cuerpo del Texto", name: "body", widget: "markdown"}
      # ⬅️ RUTA CORREGIDA: Apunta a 'content/pages/about.md'
      - file: "content/pages/about.md"
        label: "Página Nosotros"
        name: "about"
        fields:
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Contenido", name: "content", widget: "text"}

  - name: "blog" # Colección de posts (carpeta)
    label: "Blog Posts"
    # ⬅️ RUTA CORREGIDA: Apunta a la carpeta 'content/posts'
    folder: "content/posts" 
    create: true 
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Imagen destacada", name: "thumbnail", widget: "image", required: false}
      - {label: "Cuerpo", name: "body", widget: "markdown"}
