backend:
  name: git-gateway
  # La rama principal de tu repositorio.
  branch: main 

# Configuración de Medios
publish_mode: editorial_workflow
# ⚠️ IMPORTANTE: Esta carpeta DEBE existir en tu repositorio.
media_folder: "static/uploads" 
public_folder: "/uploads" 

# --- COLECCIONES ---
collections:
  - name: "pages" 
    label: "Páginas del Sitio"
    files:
      # RUTA CORREGIDA: Apunta a la carpeta 'content/pages/'
      - file: "content/pages/home.md" 
        label: "Página de Inicio"
        name: "home"
        fields:
          - {label: "Título Principal", name: "title", widget: "string"}
          - {label: "Cuerpo del Texto", name: "body", widget: "markdown"}
      # RUTA CORREGIDA: Apunta a la carpeta 'content/pages/'
      - file: "content/pages/about.md"
        label: "Página Nosotros"
        name: "about"
        fields:
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Contenido", name: "content", widget: "text"}

  - name: "blog"
    label: "Blog Posts"
    # RUTA CORREGIDA: Apunta a la carpeta 'content/posts'
    folder: "content/posts" 
    create: true 
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Imagen destacada", name: "thumbnail", widget: "image", required: false}
      - {label: "Cuerpo", name: "body", widget: "markdown"}
